apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: IMAGE_NAME_PLACEHOLDER:TAG_PLACEHOLDER # This will be replaced dynamically in the CI/CD pipeline
        ports:
        - containerPort: 8080

