version: '3.8'

services:
  demo-service:
    build:
      context: .
      dockerfile: demo/Dockerfile
    ports:
      - "8081:8080"
    networks:
      - my-network

  video-service:
    build:
      context: .
      dockerfile: video/Dockerfile
    ports:
      - "8082:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
